language: python

python:
  - "3.11"

install:
  - python3 -m pip install --upgrade pip
  - python3 -m pip install -r swe1-app/requirements.txt

script:
  - black --check swe1-app
  - flake8 swe1-app
  - coverage run swe1-app/manage.py test
  - coverage report -m

after_success:
  - coveralls

before_deploy:
  - cd "$TRAVIS_BUILD_DIR"
  - rm -f deploy.zip
  - cd swe1-app
  - zip -r ../deploy.zip . -x "*.git*" "__pycache__/*"
  - cd ..

deploy:
  provider: elasticbeanstalk
  edge: true
  region: us-east-1
  app: swe1-app
  env: poll-env
  bucket_name: "$AWS_BUCKET"
  zip_file: deploy.zip
  cleanup: false
  wait_until_deployed: true
  on:
    branch: main
